<?php

/**
 * Implements hook_form_alter
 */

function icfi_webform_recaptcha_form_alter(&$form, &$form_state, $form_id) {
  if (isset($form['#node']) && $form['#node']->status == '1') {
    $node = $form['#node'];
    if ($node->type == 'webform' && $node->field_form_type['und'][0]['value'] == '1'
      && (strpos($form_id, 'webform_client_form') !== FALSE)) { //webform with type "form"

      $excluded_webforms = array("Yale Text Program");
      if (!in_array($node->title, $excluded_webforms)) {
        // add reCaptcha
        $form['captcha'] = array(
          '#type' => 'captcha',
          '#captcha_type' => 'recaptcha/reCAPTCHA',
          '#description' => 'This question is for testing whether or not you are a human visitor and to prevent automated spam submissions.'
        );

        $form['#attached']['js'][] = drupal_get_path('module', 'icfi_webform_recaptcha') . '/js/recaptcha.js';
      }
    }
  }
}