<?php

/**
 * @file
 * Alters the poll form target action
 */
function poll_espanol_form_alter(&$form, $form_state, $form_id) {
	
	/* Make sure it's not an empty node first, otherwise there will be errors */  
	if(!empty($form['#node'])) {  
		
		/* Set the poll form id to have the Node ID */  
		if ($form_id == "poll_view_voting") {  
			
			/* Set redirects for each form */  
			switch ($form['#node']->nid) {  
				/* Box 1 */
				case 33:
					$form['#action'] = '/#yo-estoy-listo-para-parar';
					break;
				/* Box 2 */
				case 34:
					$form['#action'] = '/#quiero-ayudar-a-un-fumador';
					break;
				/* Box 3 */
				case 35:
					$form['#action'] = '/#yo-tengo-antojos-de-tabaco';
					break;
				/* Box 4 */
				case 36:
					$form['#action'] = '/#me-deslice';
					break;
				/* Box 5 */
				case 37:
					$form['#action'] = '/#quiero-proteger-a-mi-familia';
					break;
				/* Box 6 */
				case 39:
					$form['#action'] = '/#yo-fumo-a-veces';
					break;
			}
		}
	}
}

/**
 * Return content for 'latest poll' block.
 *
 * @param $node
 *   This overrides the equivalent poll function. Just copy-and-pasted.
 */
function poll_espanol_block_latest_poll_view($node) {
  global $user;
  $output = '';

  // This is necessary for shared objects because PHP doesn't copy objects, but
  // passes them by reference.  So when the objects are cached it can result in
  // the wrong output being displayed on subsequent calls.  The cloning and
  // unsetting of $node->content prevents the block output from being the same
  // as the node output.
  $node = clone $node;
  unset($node->content);

  // No 'read more' link.
  $node->readmore = FALSE;
  $node->teaser = '';

  $links = array();
  $links[] = array('title' => t('Older polls'), 'href' => 'poll', 'attributes' => array('title' => t('View the list of polls on this site.')));
  if ($node->allowvotes) {
    $links[] = array('title' => t('Results'), 'href' => 'node/' . $node->nid . '/results', 'attributes' => array('title' => t('View the current poll results.')));
  }

  $node->links = $links;

  if (!empty($node->allowvotes)) {
    $node->content['poll_view_voting'] = drupal_get_form('poll_view_voting', $node, TRUE);
    $node->content['links'] = array(
      '#theme' => 'links',
      '#links' => $node->links,
      '#weight' => 5,
    );
  }
  else {
    $node->content['poll_view_results'] = array('#markup' => poll_view_results($node, TRUE, TRUE));
  }

  return $node;
}