#!/usr/bin/env bash

## Initialize a Docksal powered Drupal 7 site
##
## Usage: fin init

# Abort if anything fails
set -e

#-------------------------- Settings --------------------------------

# PROJECT_ROOT is passed from fin.
# The following variables are configured in the '.env' file: DOCROOT, VIRTUAL_HOST.

SITE_DIRECTORY="default"
DOCROOT_PATH="${PROJECT_ROOT}/${DOCROOT}"
SITEDIR_PATH="${DOCROOT_PATH}/sites/${SITE_DIRECTORY}"
THEME_PATH="${DOCROOT_PATH}/sites/all/themes/${THEME_NAME}"
BOOTSTRAP_FRAMEWORK_URI="https://github.com/twbs/bootstrap-sass.git"
GULP_PATH="${PROJECT_ROOT}/.docksal/commands/gulp_config"

DRUSH_MAKE_FILE_INSIDE_CONTAINER="/var/www/.docksal/commands/icfid7.make.yml"
DOCROOT_PATH_INSIDE_CONTAINER="/var/www/${DOCROOT}"
SITEDIR_PATH_INSIDE_CONTAINER="${DOCROOT_PATH_INSIDE_CONTAINER}/sites/${SITE_DIRECTORY}"
THEME_PATH_INSIDE_CONTAINER="${DOCROOT_PATH_INSIDE_CONTAINER}/sites/all/themes/${THEME_NAME}"


#-------------------------- END: Settings --------------------------------

#-------------------------- Helper functions --------------------------------

# Console colors
red='\033[0;31m'
green='\033[0;32m'
green_bg='\033[42m'
yellow='\033[1;33m'
NC='\033[0m'

echo-red () { echo -e "${red}$1${NC}"; }
echo-green () { echo -e "${green}$1${NC}"; }
echo-green-bg () { echo -e "${green_bg}$1${NC}"; }
echo-yellow () { echo -e "${yellow}$1${NC}"; }

is_windows ()
{
	local res=$(uname | grep 'CYGWIN_NT')
	if [[ "$res" != "" ]]; then
		return 0
	else
		return 1
	fi
}

# Copy a settings file.
# Skips if the destination file already exists.
# @param $1 source file
# @param $2 destination file
copy_settings_file()
{
	local source="$1"
	local dest="$2"
	
	if [[ ! -f $dest ]]; then
		echo "Copying ${dest}..."
		cp $source $dest
	else
		echo-yellow "${dest} already in place."
	fi
}

#-------------------------- END: Helper functions --------------------------------

#-------------------------- Functions --------------------------------
download_drupal() 
{
   fin drush make ${DRUSH_MAKE_FILE_INSIDE_CONTAINER} ${DOCROOT_PATH_INSIDE_CONTAINER}
}

# Install site
site_install()
{
	cd ${SITEDIR_PATH}
    fin drush site-install standard --site-name="${SITE_NAME}" --account-name=admin --account-pass=admin --db-url="mysql://user:user@db/default"
}

install_modules() {
	cd ${DOCROOT_PATH}
	fin drush dis overlay -y
	for MODULE in "${MODULES[@]}"
  do :
     fin drush en ${MODULE} -y
  done
}

install_gulp() {
  fin exec "npm install -g gulp"
  cd ${PROJECT_ROOT}
  if fin exec "find ${THEME_PATH_INSIDE_CONTAINER}/gulpfile.js | read"; then
    echo "skipping Gulp config..."
  else
    echo "installing Gulp config..."
    cp ${GULP_PATH}/* ${THEME_PATH}
  fi
  fin exec "cd ${THEME_PATH_INSIDE_CONTAINER}; npm install"
  set +e
  fin gulp
  set -e
}

import_dev_db() {
cd ${DOCROOT_PATH}
fin drush sql-sync @dev @local
}

import_dev_files() {
cd ${DOCROOT_PATH}
fin drush rsync --copy-dirlinks @dev:%files @local:%files
}

create_theme() {
	cd ${DOCROOT_PATH}
	fin exec "cp -R ${DOCROOT_PATH_INSIDE_CONTAINER}/sites/all/themes/bootstrap/starterkits/sass/ ${THEME_PATH_INSIDE_CONTAINER}"
	fin exec "mv ${THEME_PATH_INSIDE_CONTAINER}/sass.starterkit ${THEME_PATH_INSIDE_CONTAINER}/${THEME_NAME}.info"
	fin exec "sed -i 's/css\/style.css/dist\/css\/style.css/' ${THEME_PATH_INSIDE_CONTAINER}/${THEME_NAME}.info"
	fin exec "sed -i 's/THEMETITLE/${THEME_NAME}/' ${THEME_PATH_INSIDE_CONTAINER}/${THEME_NAME}.info"
	fin exec "mkdir ${THEME_PATH_INSIDE_CONTAINER}/dist"
	fin exec "mkdir ${THEME_PATH_INSIDE_CONTAINER}/src"
	fin exec "mkdir ${THEME_PATH_INSIDE_CONTAINER}/src/images"
	fin exec "mkdir ${THEME_PATH_INSIDE_CONTAINER}/src/js"
	fin exec "mkdir ${THEME_PATH_INSIDE_CONTAINER}/src/fonts"
	fin exec "mv ${THEME_PATH_INSIDE_CONTAINER}/scss ${THEME_PATH_INSIDE_CONTAINER}/src/scss"
	fin exec "git clone ${BOOTSTRAP_FRAMEWORK_URI}"
	fin exec "mv bootstrap-sass  ${THEME_PATH_INSIDE_CONTAINER}/src/bootstrap"
	fin exec "sed -i 's/bootstrap\/assets\/javascripts\/bootstrap/src\/bootstrap\/assets\/javascripts\/bootstrap/g' ${THEME_PATH_INSIDE_CONTAINER}/${THEME_NAME}.info"
	fin drush en ${THEME_NAME} -y
	fin drush vset theme_default ${THEME_NAME}
}

#-------------------------- END: Functions --------------------------------

#-------------------------- Execution --------------------------------

if [[ "$PROJECT_ROOT" == "" ]]; then
	echo-red "\$PROJECT_ROOT is not set"
	exit 1
fi


if [[ $DOCKER_RUNNING == "true" ]]; then
	echo -e "${green_bg} Step 1 ${NC}${green} Recreating services...${NC}"
	fin reset -f
else
	echo -e "${green_bg} Step 1 ${NC}${green} Creating services...${NC}"
	fin up
fi

echo "Waiting 10s for MySQL to initialize...";
sleep 10

if fin exec "find ${DOCROOT_PATH_INSIDE_CONTAINER} -mindepth 1 | read"; then
echo -e "${green_bg} Step 2 ${NC}${green} Skipping Drupal Download...${NC}"
  echo -e "${green_bg} Step 3 ${NC}${green} Installing Database...${NC}"
  import_dev_db
  # TODO- can't get rsync to work with media drive mount.
  # echo -e "${green_bg} Step 3 ${NC}${green} Installing Files...${NC}"
  # import_dev_files
  echo -e "${green_bg} Step 5 ${NC}${green} Skipping Installing Theme...${NC}"

else
    echo -e "${green_bg} Step 2 ${NC}${green} Downloading Drupal...${NC}"
    download_drupal

    echo -e "${green_bg} Step 3 ${NC}${green} Installing Site...${NC}"
    time site_install

    # echo -e "${green_bg} Step 4 ${NC}${green} Installing Modules...${NC}"
    # install_modules

    echo -e "${green_bg} Step 5 ${NC}${green} Installing Theme...${NC}"
    create_theme
fi

if is_windows; then
	echo-green "Add ${VIRTUAL_HOST} to your hosts file (/etc/hosts), e.g.:"
	echo-green "192.168.64.100 ${VIRTUAL_HOST}"
	echo
fi

echo -e "${green_bg} Step 6 ${NC}${green} Installing Gulp...${NC}"
install_gulp

echo -e "${green_bg} Step 7 ${NC}${green} Installing Behat...${NC}"
fin behat features/blackbox.feature


echo -en "${green_bg} DONE! ${NC} "
echo -e "Open ${yellow}http://${VIRTUAL_HOST}${NC} in your browser to verify the setup."

#-------------------------- END: Execution --------------------------------
