#!/usr/bin/env bash

## Start Selenium server on host machine with chromedriver
##
## Usage: fin start_selenium
##

# Environment variables passed from fin:
#
#   $PROJECT_ROOT - (string) absolute path to NEAREST .docksal folder
#   $VIRTUAL_HOST - (string) ex. projectname.docksal
#   $DOCROOT - name of the docroot folder
#   $DOCKER_RUNNING - (string) "true" or "false"

java -Dwebdriver.chrome.driver=${PROJECT_ROOT}/tests/chromedriver -jar ${PROJECT_ROOT}/tests/selenium-server-standalone-3.4.0.jar