<?php

/**
 * This module exists because the systems table is corrupted for webform module.
 *
 * Version 7.x-3.19 is installed, and therefore the schema_version should be the
 * last N in hook_update_N (7321), but for some reason it is -1 in the Systems
 * table entry. This module's install file will set the schema version to 7321
 * so that we can then properly upgrade to Webforms 4.x. After this single use,
 * this module should be disabled and deleted. The same is true of print module-
 * For some reason it is -1 when it should be 7001.
 */
