<?php
/**
 * @file
 * icfi_main_menu.features.menu_links.inc
 */

/**
 * Implements hook_menu_default_menu_links().
 */
function icfi_main_menu_menu_default_menu_links() {
  $menu_links = array();

  // Exported menu link: main-menu_ask-for-help:node/341.
  $menu_links['main-menu_ask-for-help:node/341'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/341',
    'router_path' => 'node/%',
    'link_title' => 'Ask for Help',
    'options' => array(
      'identifier' => 'main-menu_ask-for-help:node/341',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -47,
    'customized' => 1,
    'parent_identifier' => 'main-menu_quitting-smoking:node/389',
  );
  // Exported menu link: main-menu_benefits-of-quitting:node/342.
  $menu_links['main-menu_benefits-of-quitting:node/342'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/342',
    'router_path' => 'node/%',
    'link_title' => 'Benefits of Quitting',
    'options' => array(
      'identifier' => 'main-menu_benefits-of-quitting:node/342',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -48,
    'customized' => 1,
    'parent_identifier' => 'main-menu_reasons-to-quit:node/339',
  );
  // Exported menu link: main-menu_busting-nrt-myths:node/351.
  $menu_links['main-menu_busting-nrt-myths:node/351'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/351',
    'router_path' => 'node/%',
    'link_title' => 'Busting NRT Myths',
    'options' => array(
      'identifier' => 'main-menu_busting-nrt-myths:node/351',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -49,
    'customized' => 1,
    'parent_identifier' => 'main-menu_medications-can-help-you-quit:node/602',
  );
  // Exported menu link: main-menu_causes-of-stress:node/245.
  $menu_links['main-menu_causes-of-stress:node/245'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/245',
    'router_path' => 'node/%',
    'link_title' => 'Causes of Stress',
    'options' => array(
      'identifier' => 'main-menu_causes-of-stress:node/245',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -49,
    'customized' => 1,
    'parent_identifier' => 'main-menu_stress-management:node/395',
  );
  // Exported menu link: main-menu_challenges-when-quitting:node/397.
  $menu_links['main-menu_challenges-when-quitting:node/397'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/397',
    'router_path' => 'node/%',
    'link_title' => 'Challenges When Quitting',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'main-menu_challenges-when-quitting:node/397',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 0,
    'weight' => -48,
    'customized' => 1,
  );
  // Exported menu link: main-menu_cravings--triggers:node/396.
  $menu_links['main-menu_cravings--triggers:node/396'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/396',
    'router_path' => 'node/%',
    'link_title' => 'Cravings & Triggers',
    'options' => array(
      'identifier' => 'main-menu_cravings--triggers:node/396',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 0,
    'weight' => -48,
    'customized' => 1,
    'parent_identifier' => 'main-menu_challenges-when-quitting:node/397',
  );
  // Exported menu link: main-menu_eat-healthy:node/393.
  $menu_links['main-menu_eat-healthy:node/393'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/393',
    'router_path' => 'node/%',
    'link_title' => 'Eat Healthy',
    'options' => array(
      'identifier' => 'main-menu_eat-healthy:node/393',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 0,
    'weight' => -49,
    'customized' => 1,
    'parent_identifier' => 'main-menu_stay-smokefree-for-good:node/410',
  );
  // Exported menu link: main-menu_explore-quit-methods:node/384.
  $menu_links['main-menu_explore-quit-methods:node/384'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/384',
    'router_path' => 'node/%',
    'link_title' => 'Explore Quit Methods',
    'options' => array(
      'identifier' => 'main-menu_explore-quit-methods:node/384',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -48,
    'customized' => 1,
    'parent_identifier' => 'main-menu_tools--tips:node/398',
  );
  // Exported menu link: main-menu_faqs-for-helping-someone-quit:node/260.
  $menu_links['main-menu_faqs-for-helping-someone-quit:node/260'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/260',
    'router_path' => 'node/%',
    'link_title' => 'FAQs for Helping Someone Quit',
    'options' => array(
      'identifier' => 'main-menu_faqs-for-helping-someone-quit:node/260',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -49,
    'customized' => 1,
    'parent_identifier' => 'main-menu_for-family--friends:node/782',
  );
  // Exported menu link: main-menu_get-active:node/394.
  $menu_links['main-menu_get-active:node/394'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/394',
    'router_path' => 'node/%',
    'link_title' => 'Get Active',
    'options' => array(
      'identifier' => 'main-menu_get-active:node/394',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 0,
    'weight' => -48,
    'customized' => 1,
    'parent_identifier' => 'main-menu_stay-smokefree-for-good:node/410',
  );
  // Exported menu link: main-menu_health-effects:node/348.
  $menu_links['main-menu_health-effects:node/348'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/348',
    'router_path' => 'node/%',
    'link_title' => 'Health Effects',
    'options' => array(
      'identifier' => 'main-menu_health-effects:node/348',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -49,
    'customized' => 1,
    'parent_identifier' => 'main-menu_reasons-to-quit:node/339',
  );
  // Exported menu link: main-menu_help-others-quit:node/392.
  $menu_links['main-menu_help-others-quit:node/392'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/392',
    'router_path' => 'node/%',
    'link_title' => 'Help Others Quit',
    'options' => array(
      'identifier' => 'main-menu_help-others-quit:node/392',
      'attributes' => array(),
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 0,
    'weight' => -45,
    'customized' => 1,
  );
  // Exported menu link: main-menu_how-10-minutes-can-be-a-workout:node/241.
  $menu_links['main-menu_how-10-minutes-can-be-a-workout:node/241'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/241',
    'router_path' => 'node/%',
    'link_title' => 'How 10 Minutes Can Be a Workout',
    'options' => array(
      'identifier' => 'main-menu_how-10-minutes-can-be-a-workout:node/241',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -47,
    'customized' => 1,
    'parent_identifier' => 'main-menu_get-active:node/394',
  );
  // Exported menu link: main-menu_how-to-manage-cravings:node/343.
  $menu_links['main-menu_how-to-manage-cravings:node/343'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/343',
    'router_path' => 'node/%',
    'link_title' => 'How to Manage Cravings',
    'options' => array(
      'identifier' => 'main-menu_how-to-manage-cravings:node/343',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
    'parent_identifier' => 'main-menu_cravings--triggers:node/396',
  );
  // Exported menu link: main-menu_how-to-support-your-quitter:node/261.
  $menu_links['main-menu_how-to-support-your-quitter:node/261'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/261',
    'router_path' => 'node/%',
    'link_title' => 'How to Support Your Quitter',
    'options' => array(
      'identifier' => 'main-menu_how-to-support-your-quitter:node/261',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
    'parent_identifier' => 'main-menu_for-family--friends:node/782',
  );
  // Exported menu link: main-menu_know-more-about-menthol-cigarettes:node/259.
  $menu_links['main-menu_know-more-about-menthol-cigarettes:node/259'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/259',
    'router_path' => 'node/%',
    'link_title' => 'Know More About Menthol Cigarettes',
    'options' => array(
      'identifier' => 'main-menu_know-more-about-menthol-cigarettes:node/259',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -49,
    'customized' => 1,
    'parent_identifier' => 'main-menu_e-cigs-menthol--dip:node/391',
  );
  // Exported menu link: main-menu_know-your-smoking-triggers:node/330.
  $menu_links['main-menu_know-your-smoking-triggers:node/330'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/330',
    'router_path' => 'node/%',
    'link_title' => 'Know Your Smoking Triggers',
    'options' => array(
      'identifier' => 'main-menu_know-your-smoking-triggers:node/330',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -49,
    'customized' => 1,
    'parent_identifier' => 'main-menu_cravings--triggers:node/396',
  );
  // Exported menu link: main-menu_make-a-weekly-activity-plan:node/254.
  $menu_links['main-menu_make-a-weekly-activity-plan:node/254'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/254',
    'router_path' => 'node/%',
    'link_title' => 'Make a Weekly Activity Plan',
    'options' => array(
      'identifier' => 'main-menu_make-a-weekly-activity-plan:node/254',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -45,
    'customized' => 1,
    'parent_identifier' => 'main-menu_get-active:node/394',
  );
  // Exported menu link: main-menu_make-food-you-love-healthier:node/269.
  $menu_links['main-menu_make-food-you-love-healthier:node/269'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/269',
    'router_path' => 'node/%',
    'link_title' => 'Make Food You Love Healthier',
    'options' => array(
      'identifier' => 'main-menu_make-food-you-love-healthier:node/269',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -46,
    'customized' => 1,
    'parent_identifier' => 'main-menu_eat-healthy:node/393',
  );
  // Exported menu link: main-menu_managing-withdrawal:node/382.
  $menu_links['main-menu_managing-withdrawal:node/382'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/382',
    'router_path' => 'node/%',
    'link_title' => 'Managing Withdrawal',
    'options' => array(
      'identifier' => 'main-menu_managing-withdrawal:node/382',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
    'parent_identifier' => 'main-menu_challenges-when-quitting:node/397',
  );
  // Exported menu link: main-menu_prepare-to-quit:node/328.
  $menu_links['main-menu_prepare-to-quit:node/328'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/328',
    'router_path' => 'node/%',
    'link_title' => 'Prepare to Quit',
    'options' => array(
      'identifier' => 'main-menu_prepare-to-quit:node/328',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
    'parent_identifier' => 'main-menu_quitting-smoking:node/389',
  );
  // Exported menu link: main-menu_quitting-dip:node/218.
  $menu_links['main-menu_quitting-dip:node/218'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/218',
    'router_path' => 'node/%',
    'link_title' => 'Quitting Dip',
    'options' => array(
      'identifier' => 'main-menu_quitting-dip:node/218',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -48,
    'customized' => 1,
    'parent_identifier' => 'main-menu_e-cigs-menthol--dip:node/391',
  );
  // Exported menu link: main-menu_quitting-smoking:node/389.
  $menu_links['main-menu_quitting-smoking:node/389'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/389',
    'router_path' => 'node/%',
    'link_title' => 'Quitting Smoking',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'main-menu_quitting-smoking:node/389',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 0,
    'weight' => -47,
    'customized' => 1,
  );
  // Exported menu link: main-menu_quiz-how-strong-is-your-nicotine-addiction:node/38.
  $menu_links['main-menu_quiz-how-strong-is-your-nicotine-addiction:node/38'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/38',
    'router_path' => 'node/%',
    'link_title' => 'Quiz: How Strong is Your Nicotine Addiction?',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'main-menu_quiz-how-strong-is-your-nicotine-addiction:node/38',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -49,
    'customized' => 1,
    'parent_identifier' => 'main-menu_managing-withdrawal:node/382',
  );
  // Exported menu link: main-menu_quiz-what-are-your-withdrawal-symptoms:node/37.
  $menu_links['main-menu_quiz-what-are-your-withdrawal-symptoms:node/37'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/37',
    'router_path' => 'node/%',
    'link_title' => 'Quiz: What Are Your Withdrawal Symptoms?',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'main-menu_quiz-what-are-your-withdrawal-symptoms:node/37',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -48,
    'customized' => 1,
    'parent_identifier' => 'main-menu_managing-withdrawal:node/382',
  );
  // Exported menu link: main-menu_reasons-to-quit:node/339.
  $menu_links['main-menu_reasons-to-quit:node/339'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/339',
    'router_path' => 'node/%',
    'link_title' => 'Reasons to Quit',
    'options' => array(
      'identifier' => 'main-menu_reasons-to-quit:node/339',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 0,
    'weight' => -46,
    'customized' => 1,
    'parent_identifier' => 'main-menu_quitting-smoking:node/389',
  );
  // Exported menu link: main-menu_resources-for-health-professionals:node/248.
  $menu_links['main-menu_resources-for-health-professionals:node/248'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/248',
    'router_path' => 'node/%',
    'link_title' => 'Resources for Health Professionals',
    'options' => array(
      'identifier' => 'main-menu_resources-for-health-professionals:node/248',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -49,
    'customized' => 1,
    'parent_identifier' => 'main-menu_for-health-professionals:node/783',
  );
  // Exported menu link: main-menu_secondhand-smoke:node/266.
  $menu_links['main-menu_secondhand-smoke:node/266'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/266',
    'router_path' => 'node/%',
    'link_title' => 'Secondhand Smoke',
    'options' => array(
      'identifier' => 'main-menu_secondhand-smoke:node/266',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -45,
    'customized' => 1,
    'parent_identifier' => 'main-menu_reasons-to-quit:node/339',
  );
  // Exported menu link: main-menu_slips--relapses:node/386.
  $menu_links['main-menu_slips--relapses:node/386'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/386',
    'router_path' => 'node/%',
    'link_title' => 'Slips & Relapses',
    'options' => array(
      'identifier' => 'main-menu_slips--relapses:node/386',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 0,
    'weight' => -46,
    'customized' => 1,
    'parent_identifier' => 'main-menu_stay-smokefree-for-good:node/410',
  );
  // Exported menu link: main-menu_slips-happen:node/387.
  $menu_links['main-menu_slips-happen:node/387'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/387',
    'router_path' => 'node/%',
    'link_title' => 'Slips Happen',
    'options' => array(
      'identifier' => 'main-menu_slips-happen:node/387',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 1,
    'parent_identifier' => 'main-menu_slips--relapses:node/386',
  );
  // Exported menu link: main-menu_smoking--depression:node/385.
  $menu_links['main-menu_smoking--depression:node/385'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/385',
    'router_path' => 'node/%',
    'link_title' => 'Smoking & Depression',
    'options' => array(
      'identifier' => 'main-menu_smoking--depression:node/385',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
    'parent_identifier' => 'main-menu_mood-management:node/780',
  );
  // Exported menu link: main-menu_speak-to-an-expert:node/329.
  $menu_links['main-menu_speak-to-an-expert:node/329'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/329',
    'router_path' => 'node/%',
    'link_title' => 'Speak to an Expert',
    'options' => array(
      'identifier' => 'main-menu_speak-to-an-expert:node/329',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -49,
    'customized' => 1,
    'parent_identifier' => 'main-menu_tools--tips:node/398',
  );
  // Exported menu link: main-menu_steps-to-manage-quit-day:node/345.
  $menu_links['main-menu_steps-to-manage-quit-day:node/345'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/345',
    'router_path' => 'node/%',
    'link_title' => 'Steps to Manage Quit Day',
    'options' => array(
      'identifier' => 'main-menu_steps-to-manage-quit-day:node/345',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -49,
    'customized' => 1,
    'parent_identifier' => 'main-menu_quitting-smoking:node/389',
  );
  // Exported menu link: main-menu_stress--smoking:node/252.
  $menu_links['main-menu_stress--smoking:node/252'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/252',
    'router_path' => 'node/%',
    'link_title' => 'Stress & Smoking',
    'options' => array(
      'identifier' => 'main-menu_stress--smoking:node/252',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
    'parent_identifier' => 'main-menu_stress-management:node/395',
  );
  // Exported menu link: main-menu_tips-for-slips:node/265.
  $menu_links['main-menu_tips-for-slips:node/265'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/265',
    'router_path' => 'node/%',
    'link_title' => 'Tips for Slips',
    'options' => array(
      'identifier' => 'main-menu_tips-for-slips:node/265',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 1,
    'parent_identifier' => 'main-menu_slips--relapses:node/386',
  );
  // Exported menu link: main-menu_tools--tips:node/398.
  $menu_links['main-menu_tools--tips:node/398'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/398',
    'router_path' => 'node/%',
    'link_title' => 'Tools & Tips',
    'options' => array(
      'identifier' => 'main-menu_tools--tips:node/398',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 0,
    'weight' => -49,
    'customized' => 1,
  );
  // Exported menu link: main-menu_understanding-depression:node/253.
  $menu_links['main-menu_understanding-depression:node/253'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/253',
    'router_path' => 'node/%',
    'link_title' => 'Understanding Depression',
    'options' => array(
      'identifier' => 'main-menu_understanding-depression:node/253',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -49,
    'customized' => 1,
    'parent_identifier' => 'main-menu_mood-management:node/780',
  );
  // Exported menu link: main-menu_understanding-withdrawal:node/327.
  $menu_links['main-menu_understanding-withdrawal:node/327'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/327',
    'router_path' => 'node/%',
    'link_title' => 'Understanding Withdrawal',
    'options' => array(
      'identifier' => 'main-menu_understanding-withdrawal:node/327',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
    'parent_identifier' => 'main-menu_managing-withdrawal:node/382',
  );
  // Exported menu link: main-menu_using-nicotine-replacement-therapy:node/352.
  $menu_links['main-menu_using-nicotine-replacement-therapy:node/352'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/352',
    'router_path' => 'node/%',
    'link_title' => 'Using Nicotine Replacement Therapy',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'main-menu_using-nicotine-replacement-therapy:node/352',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
    'parent_identifier' => 'main-menu_medications-can-help-you-quit:node/602',
  );
  // Exported menu link: main-menu_what-we-know-about-e-cigarettes:node/267.
  $menu_links['main-menu_what-we-know-about-e-cigarettes:node/267'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/267',
    'router_path' => 'node/%',
    'link_title' => 'What We Know About E-Cigarettes',
    'options' => array(
      'identifier' => 'main-menu_what-we-know-about-e-cigarettes:node/267',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
    'parent_identifier' => 'main-menu_e-cigs-menthol--dip:node/391',
  );
  // Exported menu link: main-menu_why-do-you-want-to-quit:node/340.
  $menu_links['main-menu_why-do-you-want-to-quit:node/340'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/340',
    'router_path' => 'node/%',
    'link_title' => 'Why Do You Want to Quit?',
    'options' => array(
      'identifier' => 'main-menu_why-do-you-want-to-quit:node/340',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
    'parent_identifier' => 'main-menu_reasons-to-quit:node/339',
  );
  // Exported menu link: main-menu_why-quitting-is-hard:node/247.
  $menu_links['main-menu_why-quitting-is-hard:node/247'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/247',
    'router_path' => 'node/%',
    'link_title' => 'Why Quitting Is Hard',
    'options' => array(
      'identifier' => 'main-menu_why-quitting-is-hard:node/247',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -48,
    'customized' => 1,
    'parent_identifier' => 'main-menu_quitting-smoking:node/389',
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('Ask for Help');
  t('Benefits of Quitting');
  t('Busting NRT Myths');
  t('Causes of Stress');
  t('Challenges When Quitting');
  t('Cravings & Triggers');
  t('Eat Healthy');
  t('Explore Quit Methods');
  t('FAQs for Helping Someone Quit');
  t('Get Active');
  t('Health Effects');
  t('Help Others Quit');
  t('How 10 Minutes Can Be a Workout');
  t('How to Manage Cravings');
  t('How to Support Your Quitter');
  t('Know More About Menthol Cigarettes');
  t('Know Your Smoking Triggers');
  t('Make Food You Love Healthier');
  t('Make a Weekly Activity Plan');
  t('Managing Withdrawal');
  t('Prepare to Quit');
  t('Quitting Dip');
  t('Quitting Smoking');
  t('Quiz: How Strong is Your Nicotine Addiction?');
  t('Quiz: What Are Your Withdrawal Symptoms?');
  t('Reasons to Quit');
  t('Resources for Health Professionals');
  t('Secondhand Smoke');
  t('Slips & Relapses');
  t('Slips Happen');
  t('Smoking & Depression');
  t('Speak to an Expert');
  t('Steps to Manage Quit Day');
  t('Stress & Smoking');
  t('Tips for Slips');
  t('Tools & Tips');
  t('Understanding Depression');
  t('Understanding Withdrawal');
  t('Using Nicotine Replacement Therapy');
  t('What We Know About E-Cigarettes');
  t('Why Do You Want to Quit?');
  t('Why Quitting Is Hard');

  return $menu_links;
}
