<?php

/**
* Implements hook_menu().
*/
function icfi_interactive_vet_react_app_menu() {
  return [
    'veterans/tools-help-you-quit/quit-for-good-with-nrt' => [
      'title' => 'Quit for Good with NRT',
      'page callback' => 'icfi_interactive_vet_react_app_page',
      'access callback' => TRUE,
      'type' => MENU_CALLBACK,
    ]
  ];
}

/**
 * Callback for hook_menu()
 *
 * Loads the necessary react css and js files
 */
function icfi_interactive_vet_react_app_page() {
  $base_assets_path = drupal_get_path('module', 'icfi_interactive_vet_react_app');
  $css_files = glob($base_assets_path. '/build/static/css/*.css');
  $js_files = glob($base_assets_path. '/build/static/js/*.js');
  foreach ($css_files as $css_file) {
    drupal_add_css($css_file, array(
      'scope' => 'footer',
      'group' => CSS_THEME,
      'every_page' => TRUE,
      'weight' => -2,
    ));
  }
  foreach ($js_files as $js_file) {
    drupal_add_js($js_file, array(
      'scope' => 'footer',
      'group' => JS_THEME,
      'every_page' => TRUE,
      'weight' => -2,
    ));
  }
  // create the og:description tag
  $meta_description = array(
    '#tag' => 'meta',
    '#attributes' => array(
      'name' => 'description',
      'content' => 'Nicotine replacement therapy (NRT) can double your chances of quitting for good when used correctly. Explore your NRT options—like gum, patches, and lozenges—and learn how they can be used together to fight the toughest cravings.',
    ),
  );
  drupal_add_html_head($meta_description, 'meta_description');
  return [
    '#type' => 'markup',
    '#markup' => '<div id="root"></div>',
  ];
}